### PR TITLE
Also remove arch from feature for MacOS

### PR DESCRIPTION
**Pull request by guw**

### CODE REVIEW

**Comment by fappel** [comment]
Changes are merged and ready for testing on the development repository. Just one question. I saw that you've removed also the fragment=true flag on the dependency declarations to the fragments. Are those statements superfluous?

**Comment by guw** [comment]
Oh that's a good question. I used PDE's feature editor and did not pay attention to this detail.

**Comment by guw** [comment]
Confirmed it works now on Apple Silicon:
```
g! ss codeaffine
"Framework is launched."

id	State       Bundle
2412	ACTIVE      com.codeaffine.eclipse.swt_0.8.0.20240121-0326
2413	ACTIVE      com.codeaffine.eclipse.ui.swt.theme_0.10.0.20240121-0326
	            Fragments=2414
2414	RESOLVED    com.codeaffine.eclipse.ui.swt.theme.mac_0.10.0.20240121-0326
	            Master=2413
2415	STARTING    com.codeaffine.util_0.1.0.20240121-0326
```

**Comment by fappel** [comment]
Great! Before I actually release the new version I will give it a try on a windows machine. However that will have to wait till next week. Thanks again

**Comment by fappel** [comment]
Windows check was ok and the new version has been released  Thanks for the contribution

**Pull request merged**
